export const projectMain = [
  {
    id: 1,
    company: "Swadek System Limited",
    type: "Cooperate Website",
    imageUrl: "img/v-1.png",
    link: "#",
  },
  {
    id: 2,
    company: "Alaiyingi Chambers",
    type: "Cooperate Website",
    imageUrl: "img/v-2.jfif",
    link: "#",
  },
  {
    id: 3,
    company: "Seal Optimum Limited",
    type: "Cooperate Website",
    imageUrl: "img/v-3.jfif",
    link: "#",
  },
  {
    id: 4,
    company: "Crystal Catering and Event Management",
    type: "Cooperate Website",
    imageUrl: "img/v-4.jfif",
    link: "#",
  },
  {
    id: 5,
    company: "Tigo Capital Energy Limited",
    type: "Cooperate Website",
    imageUrl: "img/v-5.jpg",
    link: "#",
  },
  {
    id: 6,
    company: "High Tech IT and Engineering",
    type: "Cooperate Website",
    imageUrl: "img/v-6.jpg",
    link: "#",
  },
  {
    id: 7,
    company: "Energydeck Limitedd",
    type: "Cooperate Website",
    imageUrl: "img/v-7.jpg",
    link: "#",
  },
  {
    id: 8,
    company: "PDGS Agency Limited",
    type: "Cooperate Website",
    imageUrl: "img/v-8.jpg",
    link: "#",
  },
];
